server:
  port: 4000
  shutdown: "graceful"

# Health + endpoints

management:
  endpoint:
    health:
      show-details: "always"
      group:
        readiness:
          include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: "health,info"

springdoc:
  packagesToScan: uk.gov.hmcts.reform.dev.controllers
  writer-with-order-by-keys: true

# Common defaults (H2 for local dev)

spring:
  config:
    import: "optional:configtree:/mnt/secrets/test/"
  application:
    name: Dev Test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mojdevtest}${DB_OPTIONS:}
    username: ${DB_USER_NAME:taskuser}
    password: ${DB_PASSWORD:taskpass}
    properties:
      charSet: UTF-8
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 10000
      pool-name: hmctsDevHikariCP
      max-lifetime: 7200000
      connection-timeout: 30000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            # silence the 'wall of text' — unnecessary exception throw about blob types
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: classpath:/db/migration